spring:
    application:
        name: trip-matcher

    threads:
        virtual:
            enabled=true:
                max: 10
                core: 5

csv:
    input-file:
        path: src/main/resources/data/taps.csv
    output-file:
        path: src/main/resources/data/trips.csv